# LDA

Latent Dirichlet Allocation (LDA) is a topic modeling technique that automatically identifies hidden topics in a collection of text documents. It groups related words into topics and estimates the probability of each topic being present in a document.

In [11]:
import pandas as pd

In [12]:
df = pd.read_csv("Mahas_Group.txt",header=None,on_bad_lines="skip",encoding='utf8')

In [13]:
df

           0                                                  1
0    6/14/26   2:12 PM - Messages and calls are end-to-end e...
1    6/15/26   10:56 AM - Mahalakshmi TVS: Plain chapati als...
2    6/15/26   12:22 PM - +91 99445 00329: Hi Maha Koozh was...
3    6/15/26   12:24 PM - Mahalakshmi TVS: Thanks Bavani.. m...
4    6/15/26   12:42 PM - +91 98431 67889: 💯 the koozh was a...
..       ...                                                ...
241   7/6/26   12:47 PM - Mahalakshmi TVS: Vadacurry alone a...
242   7/6/26      12:47 PM - +91 81245 84400: Give me 2 box mam
243   7/6/26                12:47 PM - Mahalakshmi TVS: Yes sir
244   7/6/26   2:07 PM - Mahalakshmi TVS: This message was d...
245   7/6/26   2:07 PM - Mahalakshmi TVS: This message was d...

[246 rows x 2 columns]

In [14]:
df=df.drop(0)
df.columns=['Date','Chat']
Message=df["Chat"].str.split("-",n=1,expand=True)
df["Time"]=Message[0]
Message1=Message[1].str.split(":",n=1,expand=True)
df["Name"]=Message1[0]
df["Chat"]=Message1[1]
df=df[["Date","Time","Name","Chat"]]
df

,Date,Time,Name,Chat
1,6/15/26,10:56 AM,Mahalakshmi TVS,Plain chapati also available - ₹10 / piece
2,6/15/26,12:22 PM,+91 99445 00329,Hi Maha Koozh was really cool.. making elders...
3,6/15/26,12:24 PM,Mahalakshmi TVS,Thanks Bavani.. my goal is to give healthy fo...
4,6/15/26,12:42 PM,+91 98431 67889,💯 the koozh was awesome
5,6/15/26,12:47 PM,+91 80560 26640,Hey- ma- pree- yeah your Display name is too...
...,...,...,...,...
241,7/6/26,12:47 PM,Mahalakshmi TVS,Vadacurry alone also available for ₹60 / serving
242,7/6/26,12:47 PM,+91 81245 84400,Give me 2 box mam
243,7/6/26,12:47 PM,Mahalakshmi TVS,Yes sir
244,7/6/26,2:07 PM,Mahalakshmi TVS,This message was deleted
245,7/6/26,2:07 PM,Mahalakshmi TVS,This message was deleted

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

 Create TF-IDF Document-Term Matrix

In [20]:
tfidf=TfidfVectorizer(max_df=0.95,min_df=2,stop_words='english')
dtm=tfidf.fit_transform(df["Chat"])

Create LDA model

In [21]:
from sklearn.decomposition import LatentDirichletAllocation
lda_model = LatentDirichletAllocation(n_components=5,random_state=42)
lda_model.fit(dtm)

LatentDirichletAllocation(n_components=5, random_state=42)

Display top 10 words for each topic

In [22]:
for index, topic in enumerate(lda_model.components_):
    results = [tfidf.get_feature_names_out()[i] for i in topic.argsort()[-10:]]
    print(results)

['special', 'order', 'tomorrow', 'dinner', 'thank', 'maha', 'plate', 'today', 'message', 'deleted']
['maha', 'chapati', 'chapathi', 'available', 'oil', 'message', 'aunty', '10', 'need', 'edited']
['phase', 'return', 'got', 'kirthi', 'ji', 'sorry', 'hi', 'gravy', 'sir', 'ok']
['morning', '12pm', 'place', 'ok', 'yes', '30pm', 'order', 'pa', 'omitted', 'media']
['home', 'thanks', 'time', 'need', 'bajji', 'serving', 'hi', 'sure', 'koozh', 'maha']

Get topic probabilities for each document

In [23]:
topic_results = lda_model.transform(dtm)

Assign the dominant topic

In [25]:
df = df.copy()
df["Topic"] = topic_results.argmax(axis=1)

In [27]:
df

,Date,Time,Name,Chat,Topic
1,6/15/26,10:56 AM,Mahalakshmi TVS,Plain chapati also available - ₹10 / piece,1
2,6/15/26,12:22 PM,+91 99445 00329,Hi Maha Koozh was really cool.. making elders...,0
3,6/15/26,12:24 PM,Mahalakshmi TVS,Thanks Bavani.. my goal is to give healthy fo...,1
4,6/15/26,12:42 PM,+91 98431 67889,💯 the koozh was awesome,4
5,6/15/26,12:47 PM,+91 80560 26640,Hey- ma- pree- yeah your Display name is too...,4
...,...,...,...,...,...
241,7/6/26,12:47 PM,Mahalakshmi TVS,Vadacurry alone also available for ₹60 / serving,4
242,7/6/26,12:47 PM,+91 81245 84400,Give me 2 box mam,1
243,7/6/26,12:47 PM,Mahalakshmi TVS,Yes sir,2
244,7/6/26,2:07 PM,Mahalakshmi TVS,This message was deleted,0
245,7/6/26,2:07 PM,Mahalakshmi TVS,This message was deleted,0